feat: config bundle packages
polywrap/javascript-client pull request #45
Opened 2023-06-14 05:31 UTC by dOrgJelli

2023-06-21 11:15 UTC, pileks requested changes
All-in-all looks good. Feel free to dismiss my proposition for changes if you disagree with them.

2023-06-21 11:15 UTC, pileks commented on packages/config-builder/src/bundles/index.ts
A general nit I have with our project structure is that we inline a lot of these exports under “index.ts”, instead of having them in separate files. My main reason for wanting to have an export by file (and it doesn’t have to be a default export) is that it makes it easier to locate types by filename, especially when reviewing code.

Is there any particular reason for us not doing something like this?

Again, this is just a nit :smile:

2023-06-21 11:15 UTC, pileks commented on packages/client/src/PolywrapClient.ts
> +  static async default(runtime: RuntimeName): Promise<PolywrapClient> /* $ */ {
~~I’d personally avoid such syntactic sugar in favor of teaching people to use the Config Builder, but I see the appeal.~~

~~Would we maybe consider having something like a “configOrRuntimeName” in the constructor? Basically, if a RuntimeName is supplied, we just use that runtime’s bundles.~~

2023-06-21 11:17 UTC, pileks commented on packages/client/src/PolywrapClient.ts
> +  static async default(runtime: RuntimeName): Promise<PolywrapClient> /* $ */ {
After writing this I realized that we can't do this due to the `async` nature of the package fetching. Disregard.

2023-06-21 11:17 UTC, pileks approved these changes

2023-06-22 19:55 UTC, dOrgJelli commented on packages/config-builder/src/bundles/index.ts
To help me better understand, can you highlight where this is happening?

2023-06-22 19:56 UTC, dOrgJelli commented on packages/client/src/PolywrapClient.ts
> +  static async default(runtime: RuntimeName): Promise<PolywrapClient> /* $ */ {
Yes that's the reason, async import can't happen in the constructor :/

2023-06-23 10:49 UTC, nerfZael commented on packages/client/src/__tests__/core/error-structure.spec.ts
> +import * as SysBundle from "@polywrap/sys-config-bundle-js";
I dont think the bundle is listed in dev deps of client and probably only works because of lerna

2023-06-23 10:49 UTC, nerfZael commented on integration-tests/react-app/package.json
> +    "@polywrap/client-js": "~0.10.1",
Should we add the browser and web3 bundles here to test?

2023-06-23 10:49 UTC, nerfZael commented on packages/config-bundles/sys/src/node.ts
> +  ...Common.bundle,
Since the node bundle is part of the sys js package, will we have polyfill issues in the browser (when using only the common bundle)?

2023-06-23 13:12 UTC, dOrgJelli commented on packages/config-bundles/sys/src/node.ts
> +  ...Common.bundle,
The magic that makes this work is in the package.Json of this package. See the "browser" property where we specify a browser compatible entry point. This allows us to have all deps in one package, and not have to use async imports.

2023-06-23 13:14 UTC, dOrgJelli commented on integration-tests/react-app/package.json
> +    "@polywrap/client-js": "~0.10.1",
Sure we can do that, but I've tested this to make sure it is including the sys package, and fails if it is incorrectly configured (aka the "browser" field in package.Json is removed).

2023-06-23 13:21 UTC, nerfZael commented on integration-tests/react-app/package.json
> +    "@polywrap/client-js": "~0.10.1",
Sounds good

2023-06-23 13:21 UTC, nerfZael commented on packages/config-bundles/sys/src/node.ts
> +  ...Common.bundle,
damn that's awesome

2023-06-23 13:24 UTC, nerfZael approved these changes
Great work!

2023-06-23 17:12 UTC, merged