Add github resolver to Sys common bundle
polywrap/javascript-client pull request #55
Opened 2023-07-01 01:16 UTC by krisbitney

I'm not sure if I put it in the right bundle. Let me know if I should move it!

2023-07-16 10:49 UTC, dOrgJelli requested changes

2023-07-16 10:49 UTC, dOrgJelli commented on packages/config-bundles/sys/src/common.ts
> +    uri: "wrap://ipfs/QmYPp2bQpRxR7WCoiAgWsWoiQzqxyFdqWxp1i65VW8wNv2",
Hey @krisbitney, this URI doesn't match here:
https://github.com/polywrap/uri-resolver-extensions/blob/master/implementations/github/URI.txt

2023-07-17 18:45 UTC, krisbitney commented on packages/config-bundles/sys/src/common.ts
> +    uri: "wrap://ipfs/QmYPp2bQpRxR7WCoiAgWsWoiQzqxyFdqWxp1i65VW8wNv2",
I looked into it and this URI is correct. I updated the deployment URI in the uri-resolver-extensions repo: https://github.com/polywrap/uri-resolver-extensions/pull/55

2023-07-18 17:21 UTC, dOrgJelli commented on packages/config-bundles/sys/src/common.ts
> +    uri: "wrap://ipfs/QmYPp2bQpRxR7WCoiAgWsWoiQzqxyFdqWxp1i65VW8wNv2",
okay nice, thank you!

2023-07-18 17:22 UTC, dOrgJelli approved these changes

2023-07-18 17:22 UTC, merged