fix: remove PackageToWrapperResolver from default resolver
polywrap/javascript-client pull request #8
Opened 2023-04-26 18:04 UTC by dOrgJelli

The default resolver should not automatically convert packages to wrappers. This will allow users of the client to fetch the package when calling `client.tryResolveUri(...)`.

Additionally, I've updated the `UriResolverExtensionFileReader` to properly cache the files it reads, avoiding needless `uriResolver.getFile(...)` requests.

2023-04-26 18:24 UTC, nerfZael reviewed
Can you add some tests for the caching feature of the file reader?

2023-04-26 18:24 UTC, nerfZael commented on packages/uri-resolver-extensions/src/UriResolverExtensionFileReader.ts
> +    const existingFile = this._fileCache.get(path);
What about errors? If an error happens once (e.g. intermittent network issue) then every `readFile` call will result in that error and the user will not be able to get the file.

2023-04-26 21:09 UTC, dOrgJelli commented on packages/uri-resolver-extensions/src/UriResolverExtensionFileReader.ts
> +    const existingFile = this._fileCache.get(path);
Great point! I think in the case of an error the error should be returned and the `_fileCache` entry should be reset so that a retry can occur.

2023-04-26 22:08 UTC, nerfZael requested changes

2023-04-26 22:08 UTC, nerfZael commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("sanity", async () => {
I find `sanity` names very uninformative.Can we name this `resolves a file` or something like that?

2023-04-26 22:08 UTC, nerfZael commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("retries when an error is thrown", async () => {
Maybe `can retry when an...`
Because it doesn't retry on its own. (Like e.g. the RequestSynchronizerResolver can if configured)

2023-04-26 22:08 UTC, nerfZael commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("caches files", async () => {
Can you add a parallel request cache test? (e.g. Promise.all(req1, req2))

2023-04-26 22:08 UTC, nerfZael commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +} from "@polywrap/client-js";
This project doesn't have a dependency (or dev-dep) on client-js (but because of lerna importing it still works unfortunately).
The reason for that is that tests should use a minimally configured client (and anything else) needed to test the feature.
You can check out `resolver-extensions.spec.ts` to see an example of that.

2023-04-27 03:28 UTC, dOrgJelli commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("sanity", async () => {
agreed, thank you for the suggestion

2023-04-27 03:28 UTC, dOrgJelli commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("retries when an error is thrown", async () => {
good point :+1:

2023-04-27 03:28 UTC, dOrgJelli commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +  it("caches files", async () => {
Nice catch, added!

2023-04-27 03:29 UTC, dOrgJelli commented on packages/uri-resolver-extensions/src/__tests__/uri-resolver-extension-file-reader.spec.ts
> +} from "@polywrap/client-js";
fixed

2023-04-27 03:45 UTC, merged